/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package aplicacao;

import dao.DAOFactory;
import dao.HistoricoDAO;
import dao.TrainingDAO;
import dao.UserDAO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Exercise;
import modelo.Historico;
import modelo.Training;
import modelo.User;

/**
 *
 * @author Luiz Guilherme
 */
public class frmHistorico extends javax.swing.JDialog {
    Historico historico;
    HistoricoDAO historicoDao = DAOFactory.criarHistoricoDAO();
    TrainingDAO treinoDao = DAOFactory.criarTrainingDAO();
    UserDAO usuarioDao = DAOFactory.criarUserDAO();
    /**
     * Creates new form frmHistorico
     */
    public frmHistorico(java.awt.Frame parent, boolean modal, Historico historico) {
        super(parent, modal);
        initComponents();
        
        this.historico = historico;
        
        if (historico != null){
            btnOk.setText("Editar");
            cmbUsuario.setSelectedItem(historico.getUsuario());
            cmbTreino.setSelectedItem(historico.getTreino());
            txtData.setText(historico.getData().toString());
            txtObs.setText(historico.getObservacoes());
        } else {
            btnOk.setText("Inserir");
        }
        
        carregarUsuarios();
        
        cmbTreino.setModel(new DefaultComboBoxModel<>());
        
        cmbUsuario.addActionListener(e -> carregarTreinos());
    }
    
    private void carregarUsuarios(){
        List<User> usuarios = usuarioDao.listar();
        
        DefaultComboBoxModel<User> modelo = new DefaultComboBoxModel<>();
        
        for (User usuario : usuarios){
            modelo.addElement(usuario);
        }
        
        cmbUsuario.setModel(modelo);
    }
    
    private void carregarTreinos(){
        User usuarioSelecionado = (User) cmbUsuario.getSelectedItem();
        
        if (usuarioSelecionado == null){
            cmbTreino.setModel(new DefaultComboBoxModel<>());
            return;
        }
        
        List<Training> treinos = treinoDao.listar();
        
        DefaultComboBoxModel<Training> modelo = new DefaultComboBoxModel<>();
        
        for (Training treino : treinos){
            modelo.addElement(treino);
        }
        
        cmbTreino.setModel(modelo);
    }
    
    private void cancelar() {
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente cancelar?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (opcao == 0) {
            this.dispose();
        }
    }
    
       
     private void inserir() {
         Historico historicoInserido = new Historico();
         
         historicoInserido.setUsuario((User) cmbUsuario.getSelectedItem());
         historicoInserido.setTreino((Training) cmbTreino.getSelectedItem()); 
         
         DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
         
         historicoInserido.setData(LocalDate.parse(txtData.getText(), formato));

         historicoInserido.setObservacoes(txtObs.getText());
         
         int linha = historicoDao.inserir(historicoInserido);
        if (linha > 0) {
            JOptionPane.showMessageDialog(this, "Histórico inserido com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao inserir Local.");
        } 
     }
     
     private void editar() {
        Training treinoSelecionado = (Training) cmbTreino.getSelectedItem();

    System.out.println("Treino selecionado:");
    System.out.println("Nome: " + treinoSelecionado.getName());
    System.out.println("ID: " + treinoSelecionado.getId());

    historico.setUsuario((User) cmbUsuario.getSelectedItem());
    historico.setTreino(treinoSelecionado);

    DateTimeFormatter formato =
            DateTimeFormatter.ofPattern("dd/MM/yyyy");

    historico.setData(
            LocalDate.parse(txtData.getText(), formato)
    );

    historico.setObservacoes(txtObs.getText());

    int linha = historicoDao.editar(historico);

    if (linha > 0) {
        JOptionPane.showMessageDialog(this,
                "Histórico editado com sucesso!");
    }
     
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipo1 = new javax.swing.JLabel();
        cmbUsuario = new javax.swing.JComboBox<>();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        lblTreino = new javax.swing.JLabel();
        cmbTreino = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtObs = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTipo1.setText("Usuário:");

        cmbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuarioActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        lblData.setText("Data:");

        lblTreino.setText("Treino:");

        cmbTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTreinoActionPerformed(evt);
            }
        });

        jLabel1.setText("Observações:");

        txtObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtObs, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtData)
                                    .addComponent(cmbTreino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbUsuario, javax.swing.GroupLayout.Alignment.LEADING, 0, 260, Short.MAX_VALUE))))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo1)
                    .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTreino)
                    .addComponent(cmbTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnOk))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUsuarioActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (historico != null) {
            try{
                editar();
                dispose();
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Verifique os campos numéricos: não são aceitos valores com ponto flutuante (EX.: 4,0 OU 4.0)", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            try{
                inserir();
                dispose();
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Verifique os campos numéricos:  não são aceitos valores com ponto flutuante (EX.: 4,0 OU 4.0)", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void cmbTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTreinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTreinoActionPerformed

    private void txtObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmHistorico dialog = new frmHistorico(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<modelo.Training> cmbTreino;
    private javax.swing.JComboBox<modelo.User> cmbUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblTipo1;
    private javax.swing.JLabel lblTreino;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtObs;
    // End of variables declaration//GEN-END:variables
}
