/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package aplicacao;

import dao.DAOFactory;
import dao.TrainingExerciseDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ExercicioIsometrico;
import modelo.Exercise;
import modelo.ExerciseCardio;
import modelo.ExerciseRepetition;
import modelo.Training;

/**
 *
 * @author Luiz Guilherme
 */



public class frmMostrarTreino extends javax.swing.JDialog {

    Training treino;
    TrainingExerciseDAO treinoExercicioDao = DAOFactory.criarTrainingExerciseDAO();
    /**
     * Creates new form frmMostrarTreino
     */
    public frmMostrarTreino(java.awt.Frame parent, boolean modal, Training treino) {
        super(parent, modal);
        initComponents();
        
        this.treino = treino;
        
        if( treino != null){
            lblNome.setText(treino.getName());
            lblDiaSemana.setText(treino.getDayWeek().name());
            
            if(treino.getUsuario() != null){
                lblUsuario.setText(treino.getUsuario().getName());
            } else {
                lblUsuario.setText("Usuário não possui um treino ");
            }
            
            carregarExercicios();
        
        } else {
            lblNome.setText("Treino não encontrado");
            lblDiaSemana.setText("-----");
            lblUsuario.setText("-----");
            JOptionPane.showMessageDialog(this, "Treino não encontrado", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
      
    }
    
    private void carregarExercicios(){
       
        List<Exercise> exercicios = treinoExercicioDao.listarExercicios(treino.getId());
        
        DefaultTableModel modelo = (DefaultTableModel) exercicioTable.getModel();
        
        modelo.setRowCount(0);
       
       try {
            for (Exercise exercicio : exercicios) {
                Integer series = null;
                Integer repeticoes = null;
                Double duracao = null;
                Double distancia = null;
                Double tempo = null;
                
                if(exercicio instanceof ExerciseRepetition r){
                    series = r.getSets();
                    repeticoes = r.getRepetition();
                } else if(exercicio instanceof ExerciseCardio c){
                    distancia = c.getDistancia();
                    duracao = c.getDuracao();
                } else if(exercicio instanceof ExercicioIsometrico i){
                    tempo = i.getTempoSegundos();
                } 
                
                modelo.addRow(new Object[]{
                                            exercicio.getName(), 
                                            exercicio.getType(),
                                            series, 
                                            repeticoes,
                                            duracao,
                                            distancia,
                                            tempo
                                    });
              
            }
        } catch (Exception e) {
            throw e;
        }
    
    }
    
    private void fechar(){
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente fechar?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (opcao == 0) {
            this.dispose();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblTipo1 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        exercicioTable = new javax.swing.JTable();
        lblUsuario = new javax.swing.JLabel();
        lblDiaSemana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setText("Nome");

        lblTipo1.setText("Usuário:");

        lblTipo.setText("Dia da semana:");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        exercicioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Exercício", "Tipo", "Séries", "Repetições", "Duração (min)", "Distância (km)", "Tempo (segundos)"
            }
        ));
        jScrollPane1.setViewportView(exercicioTable);

        lblUsuario.setText("Usuário");

        lblDiaSemana.setText("Dia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTipo1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTipo)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(btnFechar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblNome)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo1)
                    .addComponent(lblUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(lblDiaSemana))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
       fechar();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMostrarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMostrarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMostrarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMostrarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmMostrarTreino dialog = new frmMostrarTreino(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JTable exercicioTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiaSemana;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipo1;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
