/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacao;

import dao.*;
import enums.DayWeek;
import enums.ExerciseType;
import enums.Level;
import enums.MuscleGroups;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.*;

/**
 *
 * @author Luiz Guilherme
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    UserDAO usuarioDao = DAOFactory.criarUserDAO();
    TrainingDAO treinoDao = DAOFactory.criarTrainingDAO();
    HistoricoDAO historicoDao = DAOFactory.criarHistoricoDAO();
    ExerciseDAO exercicioDao = DAOFactory.criarExerciseDAO();

    
    DefaultTableModel modeloUsuario, modeloTreino, modeloHistorico, modeloExercicio = null;
            
    public frmPrincipal() {
        initComponents();
        modeloUsuario = (DefaultTableModel) usuarioTable.getModel();
        modeloTreino = (DefaultTableModel) treinoTable.getModel();
        modeloHistorico = (DefaultTableModel) historicoTable.getModel();
        modeloExercicio = (DefaultTableModel) exercicioTable.getModel();
               
        preencherTabelaExercicio();
        
        exercicioTable.getColumnModel().removeColumn(
                exercicioTable.getColumnModel().getColumn(10)
        );
        
        tamanhoTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void tamanhoTabela() {
 
        exercicioTable.getColumnModel().getColumn(0).setPreferredWidth(70);
        exercicioTable.getColumnModel().getColumn(1).setPreferredWidth(150);
        exercicioTable.getColumnModel().getColumn(2).setPreferredWidth(150);
        exercicioTable.getColumnModel().getColumn(3).setPreferredWidth(200);
        exercicioTable.getColumnModel().getColumn(4).setPreferredWidth(300);
        exercicioTable.getColumnModel().getColumn(5).setPreferredWidth(150);
        exercicioTable.getColumnModel().getColumn(6).setPreferredWidth(150);
        exercicioTable.getColumnModel().getColumn(7).setPreferredWidth(150);
        exercicioTable.getColumnModel().getColumn(8).setPreferredWidth(150);
        exercicioTable.getColumnModel().getColumn(9).setPreferredWidth(150);
        
        historicoTable.getColumnModel().getColumn(0).setPreferredWidth(70);
        historicoTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        historicoTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        historicoTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        historicoTable.getColumnModel().getColumn(4).setPreferredWidth(300);
    }
    
    private void sair(){
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmennte sair? ", "Aviso", JOptionPane.YES_NO_OPTION);
        
        if (opcao == 0){
            System.exit(0);
        }
    }
    
    
    
    private void preencherTabelaUsuario() {
        modeloUsuario.getDataVector().clear();
        try {
            for (User usuario : usuarioDao.listar()) {
                modeloUsuario.addRow(new Object[]{
                                            usuario.getId(), 
                                            usuario.getName(), 
                                            usuario.getAge(),
                                            usuario.getWeight(),
                                            usuario.getHeight(),
                                            usuario.getLevel()
                                    });
            }
        } catch (Exception e) {
            throw e;
        }
    }
    
    private void preencherTabelaExercicio() {
        modeloExercicio.getDataVector().clear();
        try {
            for (Exercise exercicio : exercicioDao.listar()) {
                Integer series = null;
                Integer repeticoes = null;
                Double distancia = null;
                Double duracao = null;
                Double tempo = null;
                
                if(exercicio instanceof ExerciseRepetition r){
                    series = r.getSets();
                    repeticoes = r.getRepetition();
                } else if(exercicio instanceof ExerciseCardio c){
                    distancia = c.getDistancia();
                    duracao = c.getDuracao();
                } else if(exercicio instanceof ExercicioIsometrico i){
                    tempo = i.getTempoSegundos();
                } 
                
                modeloExercicio.addRow(new Object[]{
                                            exercicio.getId(), 
                                            exercicio.getName(), 
                                            exercicio.getType(),
                                            exercicio.getMuscle(),
                                            exercicio.getDescription(),
                                            series, 
                                            repeticoes,
                                            duracao,
                                            distancia,
                                            tempo,
                                            exercicio
                                    });
              
            }
        } catch (Exception e) {
            throw e;
        }
    }
    
     private void preencherTabelaTreino() {
        modeloTreino.getDataVector().clear();
        try {
            for (Training treino : treinoDao.listar()) {
                modeloTreino.addRow(new Object[]{
                                            treino.getId(), 
                                            treino.getName(), 
                                            treino.getDayWeek(),
                                            treino.getUsuario().getId(),
                                        });
            }
        } catch (Exception e) {
            throw e;
        }
    }
     
    private void preencherTabelaHistorico() {
        modeloHistorico.getDataVector().clear();
        try {
            for (Historico historico : historicoDao.listar()) {
                modeloHistorico.addRow(new Object[]{
                                            historico.getId(), 
                                            historico.getUsuario().getName(), 
                                            historico.getTreino().getName(),
                                            historico.getData(),
                                            historico.getObservacoes()
                                        });
            }
        } catch (Exception e) {
            throw e;
        }
    }
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        painelTabulado = new javax.swing.JTabbedPane();
        tabUsuario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuarioTable = new javax.swing.JTable();
        btnApagarUsuario = new javax.swing.JButton();
        btnInserirUsuario = new javax.swing.JButton();
        btnSairUsuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        tabExercicio = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        exercicioTable = new javax.swing.JTable();
        btnApagarExercicio = new javax.swing.JButton();
        btnInserirExercicio = new javax.swing.JButton();
        btnSairExercicio = new javax.swing.JButton();
        btnEditarExercicio = new javax.swing.JButton();
        tabTreino = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        treinoTable = new javax.swing.JTable();
        btnApagarTreino = new javax.swing.JButton();
        btnInserirTreino = new javax.swing.JButton();
        btnSairTreino = new javax.swing.JButton();
        btnEditarTreino = new javax.swing.JButton();
        btnMostrarTreino = new javax.swing.JButton();
        tabHistorico = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        historicoTable = new javax.swing.JTable();
        btnApagarHistorico = new javax.swing.JButton();
        btnInserirHistorico = new javax.swing.JButton();
        btnSairHistorico = new javax.swing.JButton();
        btnEditarHistorico = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        tabUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabUsuarioFocusGained(evt);
            }
        });

        jScrollPane1.setToolTipText("");
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setName(""); // NOI18N

        usuarioTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        usuarioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Idade", "Peso", "Altura", "Nível"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usuarioTable.setToolTipText("");
        jScrollPane1.setViewportView(usuarioTable);

        btnApagarUsuario.setText("Apagar");
        btnApagarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarUsuarioActionPerformed(evt);
            }
        });

        btnInserirUsuario.setText("Inserir");
        btnInserirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirUsuarioActionPerformed(evt);
            }
        });

        btnSairUsuario.setText("Sair");
        btnSairUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairUsuarioActionPerformed(evt);
            }
        });

        btnEditarUsuario.setText("Editar");
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabUsuarioLayout = new javax.swing.GroupLayout(tabUsuario);
        tabUsuario.setLayout(tabUsuarioLayout);
        tabUsuarioLayout.setHorizontalGroup(
            tabUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabUsuarioLayout.createSequentialGroup()
                .addContainerGap(687, Short.MAX_VALUE)
                .addComponent(btnInserirUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApagarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairUsuario)
                .addGap(27, 27, 27))
            .addGroup(tabUsuarioLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        tabUsuarioLayout.setVerticalGroup(
            tabUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabUsuarioLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApagarUsuario)
                    .addComponent(btnSairUsuario)
                    .addComponent(btnInserirUsuario)
                    .addComponent(btnEditarUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelTabulado.addTab("Usuário", tabUsuario);

        exercicioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Tipo", "Grupo Muscular", "Descrição", "Séries", "Repetições", "Duração", "Distância", "Tempo", "Exercício"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(exercicioTable);

        btnApagarExercicio.setText("Apagar");
        btnApagarExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarExercicioActionPerformed(evt);
            }
        });

        btnInserirExercicio.setText("Inserir");
        btnInserirExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirExercicioActionPerformed(evt);
            }
        });

        btnSairExercicio.setText("Sair");
        btnSairExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairExercicioActionPerformed(evt);
            }
        });

        btnEditarExercicio.setText("Editar");
        btnEditarExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarExercicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabExercicioLayout = new javax.swing.GroupLayout(tabExercicio);
        tabExercicio.setLayout(tabExercicioLayout);
        tabExercicioLayout.setHorizontalGroup(
            tabExercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabExercicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabExercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(tabExercicioLayout.createSequentialGroup()
                        .addGap(0, 681, Short.MAX_VALUE)
                        .addComponent(btnInserirExercicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarExercicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApagarExercicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSairExercicio)))
                .addGap(27, 27, 27))
        );
        tabExercicioLayout.setVerticalGroup(
            tabExercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabExercicioLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(tabExercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApagarExercicio)
                    .addComponent(btnSairExercicio)
                    .addComponent(btnInserirExercicio)
                    .addComponent(btnEditarExercicio))
                .addGap(18, 18, 18))
        );

        painelTabulado.addTab("Exercício", tabExercicio);

        treinoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Dia da Semana", "ID do Usuário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(treinoTable);

        btnApagarTreino.setText("Apagar");
        btnApagarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarTreinoActionPerformed(evt);
            }
        });

        btnInserirTreino.setText("Inserir");
        btnInserirTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirTreinoActionPerformed(evt);
            }
        });

        btnSairTreino.setText("Sair");
        btnSairTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairTreinoActionPerformed(evt);
            }
        });

        btnEditarTreino.setText("Editar");
        btnEditarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTreinoActionPerformed(evt);
            }
        });

        btnMostrarTreino.setText("Mostar Treino");
        btnMostrarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTreinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabTreinoLayout = new javax.swing.GroupLayout(tabTreino);
        tabTreino.setLayout(tabTreinoLayout);
        tabTreinoLayout.setHorizontalGroup(
            tabTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTreinoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(tabTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabTreinoLayout.createSequentialGroup()
                        .addComponent(btnMostrarTreino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserirTreino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarTreino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApagarTreino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSairTreino)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabTreinoLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        tabTreinoLayout.setVerticalGroup(
            tabTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTreinoLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApagarTreino)
                    .addComponent(btnSairTreino)
                    .addComponent(btnInserirTreino)
                    .addComponent(btnEditarTreino)
                    .addComponent(btnMostrarTreino))
                .addContainerGap())
        );

        painelTabulado.addTab("Treino", tabTreino);

        historicoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome do Usuário", "Treino", "Data", "Observações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(historicoTable);

        btnApagarHistorico.setText("Apagar");
        btnApagarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarHistoricoActionPerformed(evt);
            }
        });

        btnInserirHistorico.setText("Inserir");
        btnInserirHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirHistoricoActionPerformed(evt);
            }
        });

        btnSairHistorico.setText("Sair");
        btnSairHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairHistoricoActionPerformed(evt);
            }
        });

        btnEditarHistorico.setText("Editar");
        btnEditarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabHistoricoLayout = new javax.swing.GroupLayout(tabHistorico);
        tabHistorico.setLayout(tabHistoricoLayout);
        tabHistoricoLayout.setHorizontalGroup(
            tabHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHistoricoLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabHistoricoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnInserirHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApagarHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairHistorico)
                .addGap(26, 26, 26))
        );
        tabHistoricoLayout.setVerticalGroup(
            tabHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHistoricoLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApagarHistorico)
                    .addComponent(btnSairHistorico)
                    .addComponent(btnInserirHistorico)
                    .addComponent(btnEditarHistorico))
                .addContainerGap())
        );

        painelTabulado.addTab("Historico", tabHistorico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTabulado)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTabulado)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirTreinoActionPerformed
        new frmTreino(this, true, null).setVisible(true);     
    }//GEN-LAST:event_btnInserirTreinoActionPerformed

    private void btnEditarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTreinoActionPerformed
       try {
            Integer id = (Integer) modeloTreino.getValueAt(treinoTable.getSelectedRow(), 0);
            String nome =  (String) modeloTreino.getValueAt(treinoTable.getSelectedRow(), 1);          
            DayWeek dia = (DayWeek) modeloTreino.getValueAt(treinoTable.getSelectedRow(), 2);
            Integer usuarioID = (Integer) modeloTreino.getValueAt(treinoTable.getSelectedRow(), 3);
            
            User usuario = usuarioDao.buscarPorId(usuarioID);
            
            Training treino = new Training();
            treino.setId(id);
            treino.setName(nome);
            treino.setDayWeek(dia);
            treino.setUsuario(usuario);
            
            new frmTreino(this, true, treino).setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Por favor, selecionar uma linha da tabela");
        }
    }//GEN-LAST:event_btnEditarTreinoActionPerformed

    private void btnInserirExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirExercicioActionPerformed
        new frmExercicio(this, true, null).setVisible(true);
    }//GEN-LAST:event_btnInserirExercicioActionPerformed

    private void btnEditarExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarExercicioActionPerformed
         try {
            int linhaSelecionada = exercicioTable.getSelectedRow();
            Exercise exercicio = (Exercise) modeloExercicio.getValueAt(linhaSelecionada, 10);
           
            new frmExercicio(this, true, exercicio).setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Por favor, selecionar uma linha da tabela");
        }
    }//GEN-LAST:event_btnEditarExercicioActionPerformed

    private void btnInserirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirUsuarioActionPerformed
        new frmUsuario(this, true, null).setVisible(true);
    }//GEN-LAST:event_btnInserirUsuarioActionPerformed

    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
       
        try {
            Integer id = (Integer) modeloUsuario.getValueAt(usuarioTable.getSelectedRow(), 0);
            String nome =  (String) modeloUsuario.getValueAt(usuarioTable.getSelectedRow(), 1);
            Integer idade = (Integer) modeloUsuario.getValueAt(usuarioTable.getSelectedRow(), 2);
            Double peso = (Double) modeloUsuario.getValueAt(usuarioTable.getSelectedRow(), 3);
            Double altura = (Double) modeloUsuario.getValueAt(usuarioTable.getSelectedRow(), 4);
            
            Level nivel = (Level) modeloUsuario.getValueAt(usuarioTable.getSelectedRow(), 5);
                        
              User usuario = new User();
            usuario.setId(id);
            usuario.setName(nome);
            usuario.setAge(idade);
            usuario.setWeight(peso);
            usuario.setHeight(altura);
            usuario.setLevel(nivel);
            
            new frmUsuario(this, true, usuario).setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Por favor, selecionar uma linha da tabela");
        }
    
    }//GEN-LAST:event_btnEditarUsuarioActionPerformed

    private void btnSairUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairUsuarioActionPerformed
        sair();
    }//GEN-LAST:event_btnSairUsuarioActionPerformed

    private void btnSairExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairExercicioActionPerformed
        sair();
    }//GEN-LAST:event_btnSairExercicioActionPerformed

    private void btnSairTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairTreinoActionPerformed
        sair();
    }//GEN-LAST:event_btnSairTreinoActionPerformed

    private void btnSairHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairHistoricoActionPerformed
        sair();
    }//GEN-LAST:event_btnSairHistoricoActionPerformed

    private void btnEditarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarHistoricoActionPerformed
        try {
            int linhaSelecionada = historicoTable.getSelectedRow();
            int linhaModelo = historicoTable.convertRowIndexToModel(linhaSelecionada);
            Historico historico = historicoDao.listar().get(linhaModelo);
            new frmHistorico(this, true, historico).setVisible(true);
            preencherTabelaHistorico();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Por favor, selecionar uma linha da tabela");
        }
    }//GEN-LAST:event_btnEditarHistoricoActionPerformed

    private void btnInserirHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirHistoricoActionPerformed
        new frmHistorico(this, true, null).setVisible(true);
    }//GEN-LAST:event_btnInserirHistoricoActionPerformed

    private void tabUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabUsuarioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tabUsuarioFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        preencherTabelaUsuario();
        preencherTabelaExercicio();
        preencherTabelaTreino();
        preencherTabelaHistorico();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnApagarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarUsuarioActionPerformed
        try {
            Integer id = (Integer) modeloUsuario.getValueAt(usuarioTable.getSelectedRow(), 0);

            int linha = usuarioDao.apagar(id);
            if (linha > 0) {
                modeloUsuario.removeRow(usuarioTable.getSelectedRow());
                JOptionPane.showMessageDialog(this, "Item excluído com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor, selecionar uma linha da tabela");
        }
    }//GEN-LAST:event_btnApagarUsuarioActionPerformed

    private void btnApagarExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarExercicioActionPerformed
         try {
            Integer id = (Integer) modeloExercicio.getValueAt(exercicioTable.getSelectedRow(), 0);

            int linha = exercicioDao.apagar(id);
            if (linha > 0) {
                modeloExercicio.removeRow(exercicioTable.getSelectedRow());
                JOptionPane.showMessageDialog(this, "Item excluído com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor, selecionar uma linha da tabela");
        }
    }//GEN-LAST:event_btnApagarExercicioActionPerformed

    private void btnApagarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarTreinoActionPerformed
       try {
            Integer id = (Integer) modeloTreino.getValueAt(treinoTable.getSelectedRow(), 0);

            int linha = treinoDao.apagar(id);
            if (linha > 0) {
                modeloTreino.removeRow(treinoTable.getSelectedRow());
                JOptionPane.showMessageDialog(this, "Item excluído com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor, selecionar uma linha da tabela");
        }
    }//GEN-LAST:event_btnApagarTreinoActionPerformed

    private void btnMostrarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTreinoActionPerformed
        int linha = treinoTable.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this,"Selecione um treino.");
            return;
        }
        
         int idTreino = (int) treinoTable.getValueAt(linha, 0);        
        
         Training treino = treinoDao.buscarPorId(idTreino);

         if (treino != null) {
            new frmMostrarTreino(this, true, treino).setVisible(true);   
         }    
    }//GEN-LAST:event_btnMostrarTreinoActionPerformed

    private void btnApagarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarHistoricoActionPerformed
        try {
            Integer id = (Integer) modeloTreino.getValueAt(treinoTable.getSelectedRow(), 0);

            int linha = treinoDao.apagar(id);
            if (linha > 0) {
                modeloTreino.removeRow(treinoTable.getSelectedRow());
                JOptionPane.showMessageDialog(this, "Item excluído com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor, selecionar uma linha da tabela");
        }
    }//GEN-LAST:event_btnApagarHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagarExercicio;
    private javax.swing.JButton btnApagarHistorico;
    private javax.swing.JButton btnApagarTreino;
    private javax.swing.JButton btnApagarUsuario;
    private javax.swing.JButton btnEditarExercicio;
    private javax.swing.JButton btnEditarHistorico;
    private javax.swing.JButton btnEditarTreino;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnInserirExercicio;
    private javax.swing.JButton btnInserirHistorico;
    private javax.swing.JButton btnInserirTreino;
    private javax.swing.JButton btnInserirUsuario;
    private javax.swing.JButton btnMostrarTreino;
    private javax.swing.JButton btnSairExercicio;
    private javax.swing.JButton btnSairHistorico;
    private javax.swing.JButton btnSairTreino;
    private javax.swing.JButton btnSairUsuario;
    private javax.swing.JTable exercicioTable;
    private javax.swing.JTable historicoTable;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane painelTabulado;
    private javax.swing.JPanel tabExercicio;
    private javax.swing.JPanel tabHistorico;
    private javax.swing.JPanel tabTreino;
    private javax.swing.JPanel tabUsuario;
    private javax.swing.JTable treinoTable;
    private javax.swing.JTable usuarioTable;
    // End of variables declaration//GEN-END:variables
}
